---
- name: Couchbase Configuration
  hosts: centos8.class3.com
  become: yes
  gather_facts: yes

  tasks:
    - name: Configure main node
      shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 192.168.1.250:8091  –cluster-init-username=${admin_user} –cluster-init-password=${admin_password} –cluster-init-port=8091 –cluster-init-ramsize=${cluster_ram_quota}

    - name: Create shell script for configuring main node
      action: template src=couchbase-add-node.j2 dest=/etc/addnodes.sh mode=750

    - name: Launch config script
      action: shell /etc/addnodes.sh

    - name: Rebalance the cluster
      shell: /opt/couchbase/bin/couchbase-cli rebalance -c 192.168.1.250:8091 -u ${admin_user} -p ${admin_password}

    - name: create bucket newbucket with 2 replicas
      shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 192.168.1.250:8091 –bucket=${bucket_name} –bucket-type=couchbase –bucket-port=11211 –bucket-ramsize=${bucket_ram_quota}  –bucket-replica=${num_replicas} -u ${admin_user} -p ${admin_password}

