---
# tasks file for manage_httpd
- name: copy class3.conf file for project1
  template:
    src: class3.j2
    dest: /etc/httpd/conf.d/class3.conf
    mode: '0644'
  notify:
    - restart apache

- name: copy index content
  copy:
    content: "This is ou 1st Default web server Project1 for class3 student"
    dest: /var/www/html/index.html
    mode: '0644'
  notify:
    - restart apache
