---
#Playbooks to run grafana-prometheus-exporter role
- name: Install and configure prometheus, grafana and node-expoerter
  hosts: "{{ hosts_inventory }}"
  become: true
  
  pre_tasks:
    - name: Ensure Centos 7
      assert:
        that:
          - ansible_distribution == 'CentOS'
          - ansible_distribution_version is version('7', '>=')
          - ansible_distribution_version is version('8', '<')
        msg: "Unfortunately for now only CentOS-7 is supported."

  roles:
    - role: grafana-prometheus-exporter
