---
### Play to run against centos servers
- name: playbook to install apache httpd on centos for class3 students
  hosts: centos
  become: true
  gather_facts: true

  tasks:
  - name: install apache on centos
    yum:
      name: httpd
      state: latest

  - name: ensure apache is running on all servers
    service:
      name: httpd
      state: started
      enabled: yes
