---
###Playbook to patch centos and ansible servers

- name: Update centos 7 and 8
  hosts: "{{ hosts_inventory }}"
  become: true
  gather_facts: true
  tasks:

  - name: Patch centos7 and centos8 servers
    yum:
      name: "*"
      state: latest

  - name: Reboot the server
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
