---
all:
  children:
    rhel:
      hosts:
        rhel7.class3.com:
        rhel8.class3.com:
        rhel9.class3.com:
    centos7:
      hosts:
        centos7.class3.com:
    rocky:
      hosts:
        rocky.class3.com:
    redhat:
      children:
        centos7:
        rhel:
        rocky:
    ubuntu:
      hosts:
        ubuntu.class3.com:
    other:
      children:
        rocky:
        ubuntu:
